name: Buff Profile Views

on:
  schedule:
    - cron: '*/5 * * * *' # Cứ 5 phút chạy một lần
  workflow_dispatch: # Cho phép nhấn nút chạy thủ công

jobs:
  buff:
    runs-on: ubuntu-latest
    steps:
      - name: Send requests to Komarev
        run: |
          for i in {1..100}
          do
            curl -s https://komarev.com/ghpvc/?username=NV-DuyManh > /dev/null
            echo "Request $i sent"
          done
